local K, C, L, _ = select(2, ...):unpack()
if C.Nameplate.Enable ~= true then return end

local GetSpellInfo = GetSpellInfo
----------------------------------------------------------------------------------------
--	The best way to add or delete spell is to go at http://wotlk.openwow.com search for a spell.
--	Example: Necrotic Plague> http://wotlk.openwow.com/spell=73787
--	Take the number ID at the end of the URL, and add it to the list
----------------------------------------------------------------------------------------
local function SpellName(id)
	local name = GetSpellInfo(id)
	if not name then
		if C.General.DeveloperMode then
			print("|cffFF0000budsUI:|r Invalid SpellID: "..tostring(id))
		end
		return nil
	end
	return name
end

K.DebuffWhiteList = {
	--[[ Death Knight
	[SpellName(49203)] = true,
	[SpellName(47476)] = true,
	-- Druid
	[SpellName(33786)] = true,
	[SpellName(2637)] = true,
	[SpellName(339)] = true,
	[SpellName(8921)] = true,
	[SpellName(5570)] = true,
	[SpellName(58180)] = true,
	[SpellName(33878)] = true,
	[SpellName(33745)] = true,
	[SpellName(1822)] = true,
	[SpellName(1079)] = true,
	-- Hunter
	[SpellName(3355)] = true,
	[SpellName(1513)] = true,
	[SpellName(19503)] = true,
	[SpellName(34490)] = true,
	-- Mage
	[SpellName(31661)] = true,
	[SpellName(61305)] = true,
	[SpellName(18469)] = true,
	[SpellName(122)] = true,
	[SpellName(55080)] = true,
	-- Paladin
	[SpellName(20066)] = true,
	[SpellName(10326)] = true,
	[SpellName(853)] = true,
	-- Priest
	[SpellName(605)] = true,
	[SpellName(64044)] = true,
	[SpellName(8122)] = true,
	[SpellName(9484)] = true,
	[SpellName(15487)] = true,
	-- Rogue
	[SpellName(2094)] = true,
	[SpellName(1776)] = true,
	[SpellName(6770)] = true,
	[SpellName(18425)] = true,
	-- Shaman
	[SpellName(51514)] = true,
	[SpellName(3600)] = true,
	[SpellName(8056)] = true,
	[SpellName(8050)] = true,
	[SpellName(63685)] = true,
	[SpellName(39796)] = true,
	-- Warlock
	[SpellName(710)] = true,
	[SpellName(6789)] = true,
	[SpellName(5782)] = true,
	[SpellName(5484)] = true,
	[SpellName(6358)] = true,
	[SpellName(30283)] = true,
	[SpellName(603)] = true,
	[SpellName(980)] = true,
	[SpellName(172)] = true,
	[SpellName(17800)] = true,
	[SpellName(48181)] = true,
	[SpellName(30108)] = true,
	[SpellName(348)] = true,
	-- Warrior
	[SpellName(20511)] = true,
	-- Racial
	[SpellName(25046)] = true,
	[SpellName(20549)] = true,]]
}

K.PlateBlacklist = {--[[
	["Dragonmaw War Banner"] = true,
	["Healing Tide Totem"] = true,

	--Gundrak
	["Fanged Pit Viper"] = true,
	["Crafty Snake"] = true,

	--Shaman Totems
	["Disease Cleansing Totem"] = true,
	["Earth Elemental Totem"] = true,
	["Earthbind Totem"] = true,
	["Fire Elemental Totem"] = true,
	["Fire Nova Totem I"] = true,
	["Fire Nova Totem II"] = true,
	["Fire Nova Totem III"] = true,
	["Fire Nova Totem IV"] = true,
	["Fire Nova Totem V"] = true,
	["Fire Nova Totem VI"] = true,
	["Fire Nova Totem VII"] = true,
	["Fire Resistance Totem I"] = true,
	["Fire Resistance Totem II"] = true,
	["Fire Resistance Totem III"] = true,
	["Fire Resistance Totem IV"] = true,
	["Fire Resistance Totem "] = true,
	["Flametongue Totem I"] = true,
	["Flametongue Totem II"] = true,
	["Flametongue Totem III"] = true,
	["Flametongue Totem IV"] = true,
	["Flametongue Totem V"] = true,
	["Frost Resistance Totem I"] = true,
	["Frost Resistance Totem II"] = true,
	["Frost Resistance Totem III"] = true,
	["Frost Resistance Totem IV"] = true,
	["Grace of Air Totem I"] = true,
	["Tranquil Air Totem"] = true,
	["Grace of Air Totem II"] = true,
	["Grace of Air Totem III"] = true,
	["Grounding Totem"] = true,
	["Healing Stream Totem"] = true,
	["Healing Stream Totem II"] = true,
	["Healing Stream Totem III"] = true,
	["Healing Stream Totem IV"] = true,
	["Healing Stream Totem V "] = true,
	["Healing Stream Totem VI"] = true,
	["Magma Totem"] = true,
	["Magma Totem II"] = true,
	["Magma Totem III"] = true,
	["Magma Totem IV"] = true,
	["Magma Totem V"] = true,
	["Mana Spring Totem"] = true,
	["Mana Spring Totem II"] = true,
	["Mana Spring Totem III"] = true,
	["Mana Spring Totem IV"] = true,
	["Mana Spring Totem V"] = true,
	["Mana Tide Totem"] = true,
	["Nature Resistance Totem"] = true,
	["Nature Resistance Totem II"] = true,
	["Nature Resistance Totem III"] = true,
	["Nature Resistance Totem IV"] = true,
	["Nature Resistance Totem V"] = true,
	["Nature Resistance Totem V"] = true,
	["Poison Cleansing Totem"] = true,
	["Searing Totem"] = true,
	["Searing Totem II"] = true,
	["Searing Totem III"] = true,
	["Searing Totem IV"] = true,
	["Searing Totem V"] = true,
	["Searing Totem VI"] = true,
	["Searing Totem VII"] = true,
	["Sentry Totem"] = true,
	["Stoneclaw Totem"] = true,
	["Stoneclaw Totem II"] = true,
	["Stoneclaw Totem III"] = true,
	["Stoneclaw Totem IV"] = true,
	["Stoneclaw Totem V"] = true,
	["Stoneclaw Totem VI"] = true,
	["Stoneclaw Totem VII"] = true,
	["Stoneskin Totem"] = true,
	["Stoneskin Totem II"] = true,
	["Stoneskin Totem III"] = true,
	["Stoneskin Totem IV"] = true,
	["Stoneskin Totem V"] = true,
	["Stoneskin Totem VI"] = true,
	["Stoneskin Totem VII"] = true,
	["Stoneskin Totem VIII"] = true,
	["Strength of Earth Totem"] = true,
	["Strength of Earth Totem II"] = true,
	["Strength of Earth Totem III"] = true,
	["Strength of Earth Totem IV"] = true,
	["Strength of Earth Totem V"] = true,
	["Strength of Earth Totem VI"] = true,
	["Totem of Wrath"] = true,
	["Totem of Wrath II"] = true,
	["Totem of Wrath III"] = true,
	["Totem of Wrath IV"] = true,
	["Windfury Totem"] = true,
	["Windfury Totem II"] = true,
	["Windfury Totem III"] = true,
	["Windfury Totem IV"] = true,
	["Windfury Totem V"] = true,
	["Windwall Totem"] = true,
	["Windwall Totem II"] = true,
	["Windwall Totem III"] = true,
	["Windwall Totem IV"] = true,
	["Wrath of Air Totem"] = true,

	--The gayest ability in the game
	["Army of the Dead Ghoul"] = true,

	--Hunter Trap
	["Venomous Snake"] = true,
	["Viper"] = true,]]
}

_G["NAMEPLATE_IGNORELIST"] = {
	-- All totem
	-- Enable
	["Grounding Totem"] = false,
	["Tremor Totem"] = false,
	["Mana Tide Totem"] = false,
	["Earthbind Totem"] = false,
	["Cleansing Totem"] = false,
	-- Disable
	["Nature Resistance Totem I"] = true,
	["Nature Resistance Totem II"] = true,
	["Nature Resistance Totem III"] = true,
	["Nature Resistance Totem IV"] = true,
	["Nature Resistance Totem V"] = true,
	["Nature Resistance Totem VI"] = true,
	["Sentry Totem"] = true,
	["Windfury Totem"] = true,
	["Wrath of Air Totem"] = true,
	["Earth Elemental Totem"] = true,
	["Stoneclaw Totem I"] = true,
	["Stoneclaw Totem II"] = true,
	["Stoneclaw Totem III"] = true,
	["Stoneclaw Totem IV"] = true,
	["Stoneclaw Totem V"] = true,
	["Stoneclaw Totem VI"] = true,
	["Stoneclaw Totem VII"] = true,
	["Stoneclaw Totem VIII"] = true,
	["Stoneclaw Totem IX"] = true,
	["Stoneclaw Totem X"] = true,
	["Stoneskin Totem I"] = true,
	["Stoneskin Totem II"] = true,
	["Stoneskin Totem III"] = true,
	["Stoneskin Totem IV"] = true,
	["Stoneskin Totem V"] = true,
	["Stoneskin Totem VI"] = true,
	["Stoneskin Totem VII"] = true,
	["Stoneskin Totem VIII"] = true,
	["Stoneskin Totem IX"] = true,
	["Stoneskin Totem X"] = true,
	["Strength of Earth Totem I"] = true,
	["Strength of Earth Totem II"] = true,
	["Strength of Earth Totem III"] = true,
	["Strength of Earth Totem IV"] = true,
	["Strength of Earth Totem V"] = true,
	["Strength of Earth Totem VI"] = true,
	["Strength of Earth Totem VII"] = true,
	["Strength of Earth Totem VIII;]"] = true,
	["Fire Elemental Totem"] = true,
	["Flametongue Totem I"] = true,
	["Flametongue Totem II"] = true,
	["Flametongue Totem III"] = true,
	["Flametongue Totem IV"] = true,
	["Flametongue Totem V"] = true,
	["Flametongue Totem VI"] = true,
	["Flametongue Totem VII"] = true,
	["Flametongue Totem VIII"] = true,
	["Frost Resistance Totem I"] = true,
	["Frost Resistance Totem II"] = true,
	["Frost Resistance Totem III"] = true,
	["Frost Resistance Totem IV"] = true,
	["Frost Resistance Totem V"] = true,
	["Frost Resistance Totem VI"] = true,
	["Magma Totem I"] = true,
	["Magma Totem II"] = true,
	["Magma Totem III"] = true,
	["Magma Totem IV"] = true,
	["Magma Totem V"] = true,
	["Magma Totem VI"] = true,
	["Magma Totem VII"] = true,
	["Searing Totem I"] = true,
	["Searing Totem II"] = true,
	["Searing Totem III"] = true,
	["Searing Totem IV"] = true,
	["Searing Totem V"] = true,
	["Searing Totem VI"] = true,
	["Searing Totem VII"] = true,
	["Searing Totem VIII"] = true,
	["Searing Totem IX"] = true,
	["Searing Totem X"] = true,
	["Totem of Wrath I"] = true,
	["Totem of Wrath II"] = true,
	["Totem of Wrath III"] = true,
	["Totem of Wrath IV"] = true,
	["Fire Resistance Totem I"] = true,
	["Fire Resistance Totem II"] = true,
	["Fire Resistance Totem III"] = true,
	["Fire Resistance Totem IV"] = true,
	["Fire Resistance Totem V"] = true,
	["Fire Resistance Totem VI"] = true,
	["Healing Stream Totem I"] = true,
	["Healing Stream Totem II"] = true,
	["Healing Stream Totem III"] = true,
	["Healing Stream Totem IV"] = true,
	["Healing Stream Totem V"] = true,
	["Healing Stream Totem VI"] = true,
	["Healing Stream Totem VII"] = true,
	["Healing Stream Totem VIII"] = true,
	["Healing Stream Totem IX"] = true,
	["Mana Spring Totem I"] = true,
	["Mana Spring Totem II"] = true,
	["Mana Spring Totem III"] = true,
	["Mana Spring Totem IV"] = true,
	["Mana Spring Totem V"] = true,
	["Mana Spring Totem VI"] = true,
	["Mana Spring Totem VII"] = true,
	["Mana Spring Totem VIII"] = true,

  	--The gayest ability in the game
	["Army of the Dead Ghoul"] = true,

	--Hunter Trap
	["Venomous Snake"] = true,
	["Viper"] = true,
}